services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - app-network
    env_file: "./.env"

networks:
  app-network:
    driver: bridge